package emissions;

/**
 *
 * Represents a response generated by the REST service.
 *
 * Created by pp on 21.09.17.
 */
public class Response {

    private String department;
    private String sourceType;
    private double emissions;

    public Response(String department, String sourceType, double emissions) {
        this.department = department;
        this.sourceType = sourceType;
        this.emissions = emissions;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public double getEmissions() {
        return emissions;
    }

    public void setEmissions(double emissions) {
        this.emissions = emissions;
    }
}
